services:
  - type: web
    name: dixit-jami-portfolio
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m streamlit run streamlit_app.py --server.address 0.0.0.0 --server.port $PORT --server.headless true
    autoDeploy: true
